groups:
  - name: storage
    rules:
      - alert: DiskUsageWarningVM
        expr: 100 - ((node_filesystem_avail_bytes{job="node", mountpoint="/"} / node_filesystem_size_bytes{job="node", mountpoint="/"}) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Disk usage VM {{ $labels.vm_name }} tinggi ({{ $value | printf \"%.1f\" }}%)"

      - alert: DiskUsageCriticalVM
        expr: 100 - ((node_filesystem_avail_bytes{job="node", mountpoint="/"} / node_filesystem_size_bytes{job="node", mountpoint="/"}) * 100) > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Disk usage VM {{ $labels.vm_name }} KRITIS ({{ $value | printf \"%.1f\" }}%)"

      - alert: StoragePoolUsageWarning
        expr: (pve_disk_usage_bytes / pve_disk_size_bytes * 100) * on(id) group_left(exported_node, storage) pve_storage_info > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Storage pool {{ $labels.exported_node }}/{{ $labels.storage }} tinggi ({{ $value | printf \"%.1f\" }}%)"

      - alert: StoragePoolUsageCritical
        expr: (pve_disk_usage_bytes / pve_disk_size_bytes * 100) * on(id) group_left(exported_node, storage) pve_storage_info > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Storage pool {{ $labels.exported_node }}/{{ $labels.storage }} KRITIS ({{ $value | printf \"%.1f\" }}%)"
